<template>
  <main>
    <section class="section section-browser">
      <p>
        <a href="#!home">home</a>
        <a href="#!conf">config</a>
        <a href="#!dataset/wut">dataset/wut</a>
        <a href="#!projects:dekastart">projects:dekastart</a>

      </p>
      <recent-fragments :list="fragments" :route="route"></recent-fragments>
      <p>
      {{blub}}
      </p>

    </section>

    <!-- Intro -->

    <section class="section section-editor section-intro">
      <div class="hero">
        <h1>Linked Data editor</h1>
        <p>
          This is a proof of concept for a generic Linked Data editor interface. <a href="https://schema.org">Schema.org</a> is loaded by default but should be replaceable by (and combinable with) any vocabulary.
        </p>
      </div>
      <h2>Local fragments</h2>
      <p>
        This is a list of <a href="http://linkeddatafragments.org/">fragments</a> that are stored in your browser. Changes will be saved in the browser too and can be published to a <strong>store</strong>. It's also possible to download fragments from stores.
      </p>
      <p>
        Add a fragment &mdash; Use the "Add fragment" button, adding properties is limited.
        <br>Edit a fragment &mdash; Click the fragment name (or IRI if no name).
        <br>Delete a fragment &mdash; Possible locally but not serverside.
        <br>Recursive fragment loading &mdash; Works as long as the fragment is local.
      </p>
      <h2>Stores</h2>
      <p>
        A store is a server that publishes fragments. Click a store to fetch its contents (a list of fragment IRIs). Then click a fragment to edit. Only .jsonld can be edited.
      </p>
      <p>
        Remotes return a list of fragment IRIs &mdash; Dynamically generated by a small php script.
        <br>Publish a local fragment on a remote &mdash; Works
        <br>Remotes use <a href="http://dcat.be/">DCAT</a> &mdash; To be implemented.
        <br><a href="http://thedatatank.com/">Datatank</a> integration &mdash; To be implemented.
      </p>
      <h2>Options</h2>
      <p>
        Download JSON &mdash; Download a backup that you can upload again.
        <br>Reset &mdash; Clear all local fragments. Danger!
        <br>Intro &mdash; Back to this page.
      </p>
    </section>
  </main>
</template>

<script>
export default {
  ready () {
    // console.log('home', this)
  }
}
</script>

<style lang="scss">
</style>
